version: '3.8'

services:
  flask-backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  react-frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://flask-backend:5000/
    depends_on:
      - flask-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
